[book]
title = "context-daddy"
authors = ["Robert Taylor"]
language = "en"
src = "docs"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/ChipFlow/context-daddy"
edit-url-template = "https://github.com/ChipFlow/context-daddy/edit/main/{path}"
